<?php

########################################################################
# Extension Manager/Repository config file for ext: "arm_gmap"
#
# Auto generated by Extension Builder 2013-06-01
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'ARM Google Map',
	'description' => 'jQuery based Google map. Dynamically determines position based on address, option to set width, height, zoom',
	'category' => 'plugin',
	'author' => 'Anisur R. Mullick',
	'author_email' => 'anisur@armtechnologies.com',
	'author_company' => 'ARM Technologies',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '6.0',
			'extbase' => '6.0',
			'fluid' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>